name: inventory_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  firebase_storage: ^10.3.8
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  modal_bottom_sheet: ^2.1.2
  logger: ^1.1.0
  uuid: ^3.0.6
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

